HeinrichApfelmus/threepenny-gui

src/Graphics/UI/Threepenny/Core.hs, src/Graphics/UI/Threepenny/Internal.hs, threepenny-gui.cabal
This change allows building on GHC 7.8 (I'm running 7.8.3). Not sure exactly how or why this worked before but doesn't anymore.
=> Fix build error on GHC 7.8

threepenny-gui.cabal
I can't seem to find it's purpose anyway.
=> attoparsec-enumerator not needed.

samples/DrumMachine.hs, src/Graphics/UI/Threepenny/Core.hs, src/Reactive/Threepenny.hs, src/Reactive/Threepenny/PulseLatch.hs, src/Reactive/Threepenny/Types.hs
This PR adds a straightforward implementation of event unregistration as mentioned in #122. I need this for a GUI library I'm building on top of Threepenny.
The `onEvent` function now has a different signature so that could break code but I left `on` unchanged, as I consider the latter to be the more 'higher level' function that is probably used more frequently, without need for unregistration.
=> Event unregistration

samples/BarTab.hs
On line 31
```
element elResult # set UI.text (showNumber . sum $ map readNumber xs)
```
Works correctly, while
```
element elResult # set text (showNumber . sum $ map readNumber xs)
```
makes that `<body>` tag is empty. I think instead of referring to [`Attributes.text_`](http://hackage.haskell.org/package/threepenny-gui-0.6.0.3/docs/Graphics-UI-Threepenny-Attributes.html#v:text_) it refers to [`Core.text`](http://hackage.haskell.org/package/threepenny-gui-0.6.0.3/docs/Graphics-UI-Threepenny-Core.html#v:text), which is a different function. Is that the source of the problem?
=> fixed BarTab.hs example: UI.text instead of text

doc/electron.md, doc/electron/electron.js, doc/electron/package.json
relates to #111 and #52 
I recommend reading the instructions as [rendered markdown](https://github.com/barischj/threepenny-gui/blob/feature/electron/doc/electron.md) rather than in the "Files changed" menu
- instructions included as `docs/electron.md`
- justification for Electron
- how to run with Electron
- packaging with electron-packager
-  included reference `package.json` and `electron.js` files
=> added instructions for packaging with Electron

src/Graphics/UI/Threepenny/Core.hs, src/Graphics/UI/Threepenny/Internal.hs
This is related to using a custom monad stack.
I have found using a custom monad stack useful for storing `Behavior`s, such that one part of the application can easily emit a new value, or some other part of the application `sink` that value. Simply by `ask` ing for the necessary function.
``` Haskell
-- |Monad the app runs in.
type FooMonad a = ReaderT Env UI a
-- | Enironment/config the app requires.
data Env = Env {
, eBarBehavior :: Behavior (Maybe String)
, eBarEmit     :: Handler  (Maybe String)
...
}
```
I also use a custom monad stack for a unique ID generator.
``` Haskell
-- |Return a unique ID.
uniqueId :: FooMonad String
uniqueId = do
mId <- eId <$> ask
id' <- liftIO $ MV.modifyMVar mId (\i -> return (i + 1, i))
return $ "__unique-id-" ++ show id'
```
The problem with the …
=> Added MonadUI typeclass

src/Foreign/JavaScript.hs, src/Graphics/UI/Threepenny/Core.hs, src/Graphics/UI/Threepenny/Internal.hs
As discussed, this will enable easier management of custom JSObject lifetimes, as illustrated by the new version of ffiExport.
=> Expose the underlying JSObject of an Element.

js/lib.js
Synthetic events use `CustomEvent()`, which contains a customizable `detail` attribute.  This PR allows that attribute to be passed to the Haskell side, allowing one to, say, use:
```haskell
on (domEvent "myEvent") elm $ ...
```
on the Haskell side, and:
```javascript
var ev = new CustomEvent("myEvent", { detail: ... });
elm.dispatchEvent(ev);
```
on the JavaScript side.
Cf. <https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent>
=> Add support for synthetic events (CustomEvent)

CHANGELOG.md, threepenny-gui.cabal
@HeinrichApfelmus Do you mind if I release v0.8.2.0 including the `getCookies` addition? Otherwise I'd make a v0.8.1.1 only for the version bump.
=> Allow file-embed-0.0.10.1

src/Graphics/UI/Threepenny/Events.hs
The keypress event completes the standard keydown, keypress, keyup trio, and is useful for getting hold of the actual Unicode character, as opposed to the numeric keycode.
Hope this helps!
=> Add the keypress event

samples/runhaskell.cmd
A Windows-CMD-port of the runhaskell bash-script. Tested with stack.
Using this batch running the examples as described in the README works natively on Windows (given stack has been installed before) and the command `./runhaskell` is replaced by `runhaskell.cmd`.
=> Added runhaskell-script for Windows

js/index.html
See https://forum.jquery.com/topic/ie-11-issue-d-addeventlistener-domcontentloaded-s-with-jquery-3-2-1
Without this patch `d.addEventListener("DOMContentLoaded",S);` fails. This call is in jQuery.
Maybe upgrading to a recent jQuery version (e.g. [3.3.1](https://github.com/jquery/jquery/releases)) would also work, but I shied away from that for now.
=> Invoke compatibility mode of IE11 for jQuery v3.2.1

CHANGELOG.md, threepenny-gui.cabal
The metadata changes were prompted by Hackage's refusal to accept
Cabal-version >= 1.8
=> Cabal file updates and version bump

threepenny-gui.cabal
I've tested this locally with `cabal build --constraint="bytestring>=0.11" --allow-newer=bytestring`.
=> Allow bytestring 0.11

threepenny-gui.cabal
https://hackage.haskell.org/package/text-2.0/changelog
---
I'm currently building this with
```
cabal build --constraint 'text >= 2' --allow-newer=io-streams:text,websockets:text,snap-server:text,blaze-builder:text,snap-core:text,aeson:text,uuid-types:text,snap-core:hashable,scientific:text,text-short:text,strict:text,snap-server:attoparsec,io-streams-haproxy:attoparsec,snap-core:attoparsec
```
This is mainly blocked on `aeson`, which will need a new release. The other dependencies already _build_ fine.
---
BTW: Merry Christmas, @HeinrichApfelmus and every else who sees this! :)
=> Allow text-2.0

threepenny-gui.cabal
https://hackage.haskell.org/package/vector-0.13.0.0/changelog
---
Blocked on:
Current incantation:
```
cabal build --constraint 'vector >= 0.13' -w ghc-8.10 --allow-newer=io-streams:vector,snap-server:vector,snap-core:vector,snap-server:attoparsec
```
=> Allow vector-0.13

.github/workflows/haskell-ci.yml, threepenny-gui.cabal
A number of dependencies still have incompatible bounds.
Build command as of 2022-08-10:
```
$ cabal build -w ghc-9.4 all --allow-newer=async:base,text-short:base,text-short:ghc-prim,text-short:template-haskell,serialise:base,serialise:ghc-prim,these:base,assoc:base,scientific:base,vector:base,scientific:template-haskell,integer-logarithms:base,integer-logarithms:ghc-prim,integer-logarithms:ghc-bignum,indexed-traversable:base,hashable:base,hashable:ghc-bignum,aeson:ghc-prim,data-fix:base,aeson:template-haskell,indexed-traversable-instances:base,uuid-types:template-haskell,time-compat:base,semialign:base,attoparsec:ghc-prim,splitmix:base,OneTuple:base,io-streams:time,snap-server:base,websockets-snap:bytestring,snap-server:attoparsec,snap-server:text,io-streams-haproxy:base,io-streams-haprox …
```
=> Support GHC 9.2 and 9.4

threepenny-gui.cabal
https://hackage.haskell.org/package/transformers-0.6.0.0/changelog
---
Build command as of 2022-05-10:
```
cabal build --constraint 'transformers >= 0.6' -w ghc-8.10 --allow-newer=websockets-snap:mtl,io-streams:transformers,snap-server:mtl,io-streams-haproxy:transformers,snap-core:mtl,snap-core:transformers
```
Blocked on:
Bounds only (I guess):
=> Allow transformers 0.6

.github/workflows/build-haskell.yml, samples/DrumMachine.hs, threepenny-gui.cabal
Due to the fact that there is a code change (hiding import of `unzip` from `Data.Function`) his will require a new Hackage release.
=> Make it build with ghc-9.8

lib/threepenny-gui/CHANGELOG.md, lib/threepenny-gui/src/Graphics/UI/Threepenny/Core.hs, lib/threepenny-gui/src/Graphics/UI/Threepenny/Internal.hs, lib/threepenny-gui/threepenny-gui.cabal
This pull request removes the dependency on the `exceptions` package.
The goal is to reduce the dependency footprint until the package can be compiled with MicroHs.
=> Remove dependency on `exceptions`

lib/javascript-ffi-threepenny/src/Foreign/JavaScript/Functions.hs, lib/javascript-ffi-threepenny/src/Foreign/JavaScript/Server.hs, lib/threepenny-gui/samples/BarTab.hs, lib/threepenny-gui/samples/Buttons.hs, lib/threepenny-gui/samples/CRUD.hs, lib/threepenny-gui/samples/Canvas.hs, lib/threepenny-gui/samples/Chat.hs, lib/threepenny-gui/samples/CurrencyConverter.hs, lib/threepenny-gui/samples/DragNDropExample.hs, lib/threepenny-gui/samples/DrumMachine.hs, lib/threepenny-gui/samples/FadeInFadeOut.hs, lib/threepenny-gui/samples/Svg.hs, lib/threepenny-gui/src/Graphics/UI/Threepenny/Core.hs, lib/threepenny-gui/src/Graphics/UI/Threepenny/Internal.hs, lib/threepenny-gui/src/Graphics/UI/Threepenny/Server.hs, lib/threepenny-gui/threepenny-gui.cabal
This pull request splits off a module `Graphics.UI.Threepenny.Server`.
The goal is that the rest of the library without this module can be compiled with MicroHs.
=> Split off module `Graphics.UI.Threepenny.Server`
